const CATEGORIES=['Bags','Dresses','Jewellery','Hair Accessories','Travel Bags','Winter Collection','Summer Collection','Wedding','Home Décor','Shoes','Other'];
const SESSION_COOKIE='ss_admin_session';
const SESSION_HOURS=12;
const PBKDF2_ITERATIONS=10000;
function json(data,status=200,extra={}){const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extra});return new Response(JSON.stringify(data),{status,headers:h})}
async function requestJson(request){try{return await request.json()}catch{return {}}}
function hex(bytes){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function fromHex(s){const a=new Uint8Array(s.length/2);for(let i=0;i<a.length;i++)a[i]=parseInt(s.slice(i*2,i*2+2),16);return a}
async function sha256(s){const b=typeof s==='string'?new TextEncoder().encode(s):s;return hex(await crypto.subtle.digest('SHA-256',b))}
async function passwordHash(password,saltHex){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:fromHex(saltHex),iterations:PBKDF2_ITERATIONS},key,256);return hex(bits)}
function randomHex(n=32){const a=new Uint8Array(n);crypto.getRandomValues(a);return hex(a)}
function secureEqualHex(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;const x=fromHex(a),y=fromHex(b);let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0}
function validMutationOrigin(request){const origin=request.headers.get('origin');if(!origin)return true;return origin===new URL(request.url).origin}
function cookies(request){const out={};for(const p of (request.headers.get('cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
function sessionCookie(token,maxAge=SESSION_HOURS*3600){return `${SESSION_COOKIE}=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`}
function clearCookie(){return `${SESSION_COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`}
function perms(user){try{return JSON.parse(user.permissions_json||'{}')}catch{return {}}}
function can(user,permission){if(!user)return false;if(user.role==='owner')return true;const p=perms(user);return p.all===true||p[permission]===true||Array.isArray(p)&&p.includes(permission)}
async function currentUser(request,env){const token=cookies(request)[SESSION_COOKIE];if(!token)return null;const th=await sha256(token);const user=await env.DB.prepare(`SELECT u.* FROM admin_sessions s JOIN admin_users u ON u.id=s.admin_user_id WHERE s.token_hash=? AND s.expires_at>CURRENT_TIMESTAMP AND u.is_active=1`).bind(th).first();return user||null}
async function requireUser(request,env,permission){const u=await currentUser(request,env);if(!u)return {error:json({ok:false,error:'Authentication required'},401)};if(permission&&!can(u,permission))return {error:json({ok:false,error:'Permission denied'},403)};return {user:u}}
async function audit(env,user,action,type,id,details={}){await env.DB.prepare('INSERT INTO audit_log(admin_user_id,action,entity_type,entity_id,details_json) VALUES(?,?,?,?,?)').bind(user?.id||null,action,type||null,id==null?null:String(id),JSON.stringify(details)).run()}
function mediaUrl(row){if(row?.r2_key)return '/media/'+row.r2_key.split('/').map(encodeURIComponent).join('/');return row?.asset_url||''}
async function releaseExpired(env){const now=new Date().toISOString();const expired=await env.DB.prepare("SELECT order_no FROM orders WHERE payment_status='pending' AND order_status IN ('reserved','payment_pending') AND payment_due_at IS NOT NULL AND payment_due_at < ?").bind(now).all();for(const o of expired.results||[]){await env.DB.batch([env.DB.prepare("UPDATE products SET status='available',reserved_order_no=NULL,reserved_until=NULL,updated_at=CURRENT_TIMESTAMP WHERE reserved_order_no=? AND status='reserved'").bind(o.order_no),env.DB.prepare("UPDATE orders SET order_status='revoked',updated_at=CURRENT_TIMESTAMP WHERE order_no=?").bind(o.order_no)]);}return expired.results?.length||0}
function orderNo(){const d=new Date();return `SS-${d.getUTCFullYear()}-${String(Date.now()).slice(-6)}`}
function discounted(p){const price=Number(p.price_pkr)||0,v=Number(p.discount_value)||0;return p.discount_type==='fixed'?Math.max(0,price-v):Math.round(price*(1-v/100))}
function fileKind(file){const t=(file.type||'').toLowerCase();return t.startsWith('video/')?'video':'image'}
async function putFile(env,file,prefix){if(!(file instanceof File)||!file.size)throw new Error('File required');const kind=fileKind(file);const max=kind==='video'?20*1024*1024:8*1024*1024;if(file.size>max)throw new Error(`${kind==='video'?'Video':'Image'} exceeds UAT limit (${kind==='video'?'20 MB':'8 MB'})`);const ext=(file.name.split('.').pop()|| (kind==='video'?'mp4':'jpg')).replace(/[^a-zA-Z0-9]/g,'').slice(0,8);const key=`${prefix}/${Date.now()}-${crypto.randomUUID()}.${ext}`;await env.FILES.put(key,file.stream(),{httpMetadata:{contentType:file.type||'application/octet-stream'},customMetadata:{originalName:file.name}});return {key,kind,size:file.size}}
async function parseForm(request){return await request.formData()}
function productSelect(){return `SELECT p.*, (SELECT r2_key FROM product_media pm WHERE pm.product_id=p.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_r2_key,(SELECT asset_url FROM product_media pm WHERE pm.product_id=p.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_asset_url FROM products p`}
async function adminRoutes(request,env,u,p,m){
 if(p.startsWith('/api/admin/')&&['POST','PATCH','PUT','DELETE'].includes(m)&&!validMutationOrigin(request))return json({ok:false,error:'Invalid request origin'},403);
 if(p==='/api/admin/login'&&m==='POST'){const b=await requestJson(request);const user=await env.DB.prepare('SELECT * FROM admin_users WHERE login_id=? AND is_active=1').bind(String(b.login_id||'').trim()).first();if(!user||!user.password_hash||!user.password_salt)return json({ok:false,error:'Invalid login ID or password'},401);const ph=await passwordHash(String(b.password||''),user.password_salt);if(!secureEqualHex(ph,user.password_hash))return json({ok:false,error:'Invalid login ID or password'},401);const token=randomHex(32),th=await sha256(token),exp=new Date(Date.now()+SESSION_HOURS*3600000).toISOString();await env.DB.prepare('INSERT INTO admin_sessions(admin_user_id,token_hash,expires_at) VALUES(?,?,?)').bind(user.id,th,exp).run();await audit(env,user,'login','admin_user',user.id);return json({ok:true,user:{id:user.id,login_id:user.login_id,display_name:user.display_name,role:user.role,permissions:perms(user)}},200,{'set-cookie':sessionCookie(token)});}
 if(p==='/api/admin/logout'&&m==='POST'){const token=cookies(request)[SESSION_COOKIE];if(token)await env.DB.prepare('DELETE FROM admin_sessions WHERE token_hash=?').bind(await sha256(token)).run();return json({ok:true},200,{'set-cookie':clearCookie()});}
 if(p==='/api/admin/me'&&m==='GET'){const a=await requireUser(request,env);if(a.error)return a.error;return json({ok:true,user:{id:a.user.id,login_id:a.user.login_id,display_name:a.user.display_name,role:a.user.role,permissions:perms(a.user)}});}
 if(p==='/api/admin/password'&&m==='POST'){const a=await requireUser(request,env);if(a.error)return a.error;const b=await requestJson(request);if(String(b.new_password||'').length<10)return json({ok:false,error:'New password must be at least 10 characters'},400);const salt=randomHex(16),hash=await passwordHash(b.new_password,salt);await env.DB.prepare('UPDATE admin_users SET password_hash=?,password_salt=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(hash,salt,a.user.id).run();await env.DB.prepare('DELETE FROM admin_sessions WHERE admin_user_id=?').bind(a.user.id).run();await audit(env,a.user,'password_changed','admin_user',a.user.id);return json({ok:true,message:'Password changed. Please login again.'},200,{'set-cookie':clearCookie()});}
 if(p==='/api/admin/summary'&&m==='GET'){const a=await requireUser(request,env);if(a.error)return a.error;const [products,orders,returns,users]=await Promise.all([env.DB.prepare("SELECT COUNT(*) n, SUM(status='available') available, SUM(status='reserved') reserved, SUM(status='sold_locked') sold FROM products").first(),env.DB.prepare("SELECT COUNT(*) n, SUM(payment_status='pending') payment_pending, SUM(order_status='dispatched') dispatched FROM orders").first(),env.DB.prepare("SELECT COUNT(*) n, SUM(status NOT IN ('refunded','rejected')) open FROM returns").first(),env.DB.prepare("SELECT COUNT(*) n FROM admin_users WHERE is_active=1").first()]);return json({ok:true,summary:{products,orders,returns,active_users:users?.n||0}});}
 if(p==='/api/admin/products'&&m==='GET'){const a=await requireUser(request,env,'products');if(a.error)return a.error;const r=await env.DB.prepare(productSelect()+' ORDER BY p.id DESC').all();return json({ok:true,products:(r.results||[]).map(x=>({...x,image_url:x.primary_r2_key?'/media/'+x.primary_r2_key.split('/').map(encodeURIComponent).join('/'):(x.primary_asset_url||'')}))});}
 if(p==='/api/admin/products'&&m==='POST'){const a=await requireUser(request,env,'products');if(a.error)return a.error;const f=await parseForm(request);const code=String(f.get('code')||'').trim().toUpperCase(),name=String(f.get('name')||'').trim(),category=String(f.get('category')||'').trim();if(!code||!name||!CATEGORIES.includes(category))return json({ok:false,error:'Code, name and valid category are required'},400);const price=Math.max(0,Number(f.get('price_pkr'))||0),discount=Math.max(0,Number(f.get('discount_value'))||0),status=String(f.get('status')||'available');const ins=await env.DB.prepare(`INSERT INTO products(code,name,category,description,price_pkr,discount_type,discount_value,status,unique_piece,featured) VALUES(?,?,?,?,?,'percent',?,?,1,?)`).bind(code,name,category,String(f.get('description')||''),price,discount,status,f.get('featured')==='1'?1:0).run();const id=ins.meta.last_row_id;const files=f.getAll('media').filter(x=>x instanceof File&&x.size);let sort=0;for(const file of files){const up=await putFile(env,file,`products/${code}`);await env.DB.prepare('INSERT INTO product_media(product_id,media_type,r2_key,is_primary,sort_order) VALUES(?,?,?,?,?)').bind(id,up.kind,up.key,sort===0?1:0,sort++).run();}await audit(env,a.user,'product_created','product',id,{code,name,media:files.length});return json({ok:true,id,message:'Product saved and published'},201);}
 if(p.match(/^\/api\/admin\/products\/\d+$/)&&m==='PATCH'){const a=await requireUser(request,env,'products');if(a.error)return a.error;const id=Number(p.split('/').pop()),b=await requestJson(request);const old=await env.DB.prepare('SELECT * FROM products WHERE id=?').bind(id).first();if(!old)return json({ok:false,error:'Product not found'},404);const name=String(b.name??old.name),category=String(b.category??old.category),description=String(b.description??old.description??''),price=Math.max(0,Number(b.price_pkr??old.price_pkr)||0),discount=Math.max(0,Number(b.discount_value??old.discount_value)||0),featured=b.featured==null?old.featured:(b.featured?1:0);let status=String(b.status??old.status);if(old.status==='sold_locked'&&status!=='sold_locked'&&a.user.role!=='owner')return json({ok:false,error:'Only Owner may change a Sold & Locked item'},403);await env.DB.prepare('UPDATE products SET name=?,category=?,description=?,price_pkr=?,discount_value=?,status=?,featured=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(name,category,description,price,discount,status,featured,id).run();await audit(env,a.user,'product_updated','product',id,{before:{price:old.price_pkr,status:old.status},after:{price,status}});return json({ok:true});}
 if(p.match(/^\/api\/admin\/products\/\d+\/media$/)&&m==='POST'){const a=await requireUser(request,env,'products');if(a.error)return a.error;const id=Number(p.split('/')[4]),prod=await env.DB.prepare('SELECT * FROM products WHERE id=?').bind(id).first();if(!prod)return json({ok:false,error:'Product not found'},404);const f=await parseForm(request),files=f.getAll('media').filter(x=>x instanceof File&&x.size);const c=await env.DB.prepare('SELECT COUNT(*) n FROM product_media WHERE product_id=?').bind(id).first();let sort=Number(c?.n||0);for(const file of files){const up=await putFile(env,file,`products/${prod.code}`);await env.DB.prepare('INSERT INTO product_media(product_id,media_type,r2_key,is_primary,sort_order) VALUES(?,?,?,?,?)').bind(id,up.kind,up.key,sort===0?1:0,sort++).run();}await audit(env,a.user,'product_media_added','product',id,{count:files.length});return json({ok:true,count:files.length});}
 if(p==='/api/admin/users'&&m==='GET'){const a=await requireUser(request,env);if(a.error)return a.error;if(a.user.role!=='owner')return json({ok:false,error:'Owner only'},403);const r=await env.DB.prepare('SELECT id,login_id,display_name,role,permissions_json,is_active,created_at FROM admin_users ORDER BY id').all();return json({ok:true,users:(r.results||[]).map(x=>({...x,permissions:perms(x)}))});}
 if(p==='/api/admin/users'&&m==='POST'){const a=await requireUser(request,env);if(a.error)return a.error;if(a.user.role!=='owner')return json({ok:false,error:'Owner only'},403);const b=await requestJson(request),login=String(b.login_id||'').trim();if(!login||String(b.password||'').length<10)return json({ok:false,error:'Login ID and password of at least 10 characters required'},400);const salt=randomHex(16),hash=await passwordHash(b.password,salt),role=['admin','agent'].includes(b.role)?b.role:'agent',pj=JSON.stringify(b.permissions||{});const r=await env.DB.prepare('INSERT INTO admin_users(login_id,display_name,password_hash,password_salt,role,permissions_json,is_active) VALUES(?,?,?,?,?,?,1)').bind(login,String(b.display_name||login),hash,salt,role,pj).run();await audit(env,a.user,'user_created','admin_user',r.meta.last_row_id,{login,role,permissions:b.permissions||{}});return json({ok:true,id:r.meta.last_row_id},201);}
 if(p.match(/^\/api\/admin\/users\/\d+$/)&&m==='PATCH'){const a=await requireUser(request,env);if(a.error)return a.error;if(a.user.role!=='owner')return json({ok:false,error:'Owner only'},403);const id=Number(p.split('/').pop());if(id===a.user.id)return json({ok:false,error:'Owner cannot disable own account here'},400);const b=await requestJson(request);const cur=await env.DB.prepare('SELECT * FROM admin_users WHERE id=?').bind(id).first();if(!cur||cur.role==='owner')return json({ok:false,error:'Protected account'},400);const active=b.is_active==null?cur.is_active:(b.is_active?1:0),role=['admin','agent'].includes(b.role)?b.role:cur.role,pj=JSON.stringify(b.permissions??perms(cur));await env.DB.prepare('UPDATE admin_users SET is_active=?,role=?,permissions_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(active,role,pj,id).run();if(!active)await env.DB.prepare('DELETE FROM admin_sessions WHERE admin_user_id=?').bind(id).run();await audit(env,a.user,'user_updated','admin_user',id,{active,role,permissions:b.permissions??perms(cur)});return json({ok:true});}
 if(p==='/api/admin/orders'&&m==='GET'){const a=await requireUser(request,env,'orders');if(a.error)return a.error;const r=await env.DB.prepare(`SELECT o.*, GROUP_CONCAT(oi.product_snapshot_code||' - '||oi.product_snapshot_name,' | ') items FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id GROUP BY o.id ORDER BY o.id DESC LIMIT 200`).all();return json({ok:true,orders:r.results||[]});}
 if(p.match(/^\/api\/admin\/orders\/\d+$/)&&m==='PATCH'){const a=await requireUser(request,env,'orders');if(a.error)return a.error;const id=Number(p.split('/').pop()),b=await requestJson(request),o=await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(id).first();if(!o)return json({ok:false,error:'Order not found'},404);if(b.action==='confirm_payment'){await env.DB.batch([env.DB.prepare("UPDATE orders SET payment_status='confirmed',order_status='paid',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id),env.DB.prepare("UPDATE products SET status='sold_locked',reserved_until=NULL,updated_at=CURRENT_TIMESTAMP WHERE reserved_order_no=?").bind(o.order_no)]);await audit(env,a.user,'payment_confirmed','order',id,{order_no:o.order_no});return json({ok:true,whatsapp_message:`Your payment for Order No. ${o.order_no} has been received by SS Collections. Your order will be dispatched within 3 working days and a confirmation message along with tracking ID will be shared with you via WhatsApp.\n\nRegards,\nSS Collections`});}if(b.action==='dispatch'){await env.DB.prepare("UPDATE orders SET order_status='dispatched',courier_name=?,tracking_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(String(b.courier_name||''),String(b.tracking_id||''),id).run();await audit(env,a.user,'order_dispatched','order',id,{courier:b.courier_name,tracking:b.tracking_id});return json({ok:true});}if(b.action==='status'){await env.DB.prepare('UPDATE orders SET order_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(String(b.order_status||o.order_status),id).run();await audit(env,a.user,'order_status_updated','order',id,{status:b.order_status});return json({ok:true});}return json({ok:false,error:'Unknown order action'},400);}
 if(p.match(/^\/api\/admin\/orders\/\d+\/media$/)&&m==='POST'){const a=await requireUser(request,env,'orders');if(a.error)return a.error;const id=Number(p.split('/')[4]),f=await parseForm(request),kind=String(f.get('media_type')||'product_before_dispatch'),files=f.getAll('media').filter(x=>x instanceof File&&x.size);for(const file of files){const up=await putFile(env,file,`orders/${id}/${kind}`);await env.DB.prepare('INSERT INTO order_media(order_id,media_type,file_type,r2_key,caption) VALUES(?,?,?,?,?)').bind(id,kind,up.kind,up.key,String(f.get('caption')||'')).run();}await audit(env,a.user,'order_media_added','order',id,{kind,count:files.length});return json({ok:true,count:files.length});}
 if(p==='/api/admin/events'&&m==='GET'){const a=await requireUser(request,env,'events');if(a.error)return a.error;const r=await env.DB.prepare('SELECT * FROM events ORDER BY event_date DESC,id DESC').all();return json({ok:true,events:r.results||[]});}
 if(p==='/api/admin/events'&&m==='POST'){const a=await requireUser(request,env,'events');if(a.error)return a.error;const f=await parseForm(request);let mediaKey=null;const file=f.get('media');if(file instanceof File&&file.size)mediaKey=(await putFile(env,file,'events')).key;const r=await env.DB.prepare('INSERT INTO events(title,city,venue,stall_no,event_date,timing,maps_url,media_r2_key,details,status) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(String(f.get('title')||''),String(f.get('city')||''),String(f.get('venue')||''),String(f.get('stall_no')||''),String(f.get('event_date')||''),String(f.get('timing')||''),String(f.get('maps_url')||''),mediaKey,String(f.get('details')||''),String(f.get('status')||'upcoming')).run();await audit(env,a.user,'event_created','event',r.meta.last_row_id);return json({ok:true,id:r.meta.last_row_id},201);}
 if(p==='/api/admin/creations'&&m==='GET'){const a=await requireUser(request,env,'creations');if(a.error)return a.error;const r=await env.DB.prepare('SELECT * FROM creations ORDER BY id DESC').all();return json({ok:true,creations:r.results||[]});}
 if(p==='/api/admin/creations'&&m==='POST'){const a=await requireUser(request,env,'creations');if(a.error)return a.error;const f=await parseForm(request),code=String(f.get('code')||'').trim().toUpperCase();const r=await env.DB.prepare('INSERT INTO creations(code,title,category,status,season,note,custom_possible) VALUES(?,?,?,?,?,?,?)').bind(code,String(f.get('title')||''),String(f.get('category')||'Other'),String(f.get('status')||'Past Collection'),String(f.get('season')||''),String(f.get('note')||''),f.get('custom_possible')==='0'?0:1).run();const id=r.meta.last_row_id,files=f.getAll('media').filter(x=>x instanceof File&&x.size);let sort=0;for(const file of files){const up=await putFile(env,file,`creations/${code}`);await env.DB.prepare('INSERT INTO creation_media(creation_id,media_type,r2_key,is_primary,sort_order) VALUES(?,?,?,?,?)').bind(id,up.kind,up.key,sort===0?1:0,sort++).run();}await audit(env,a.user,'creation_created','creation',id,{code,media:files.length});return json({ok:true,id},201);}
 if(p==='/api/admin/journey'&&m==='GET'){const a=await requireUser(request,env,'journey');if(a.error)return a.error;const r=await env.DB.prepare('SELECT * FROM handmade_journey ORDER BY id DESC').all();return json({ok:true,journey:r.results||[]});}
 if(p==='/api/admin/journey'&&m==='POST'){const a=await requireUser(request,env,'journey');if(a.error)return a.error;const f=await parseForm(request),file=f.get('media');let r2=null,mediaType='video';if(file instanceof File&&file.size){const up=await putFile(env,file,'journey');r2=up.key;mediaType=up.kind}const r=await env.DB.prepare('INSERT INTO handmade_journey(title,description,stage,media_type,r2_key,external_url,is_published,sort_order) VALUES(?,?,?,?,?,?,?,?)').bind(String(f.get('title')||''),String(f.get('description')||''),String(f.get('stage')||''),mediaType,r2,String(f.get('external_url')||''),f.get('is_published')==='0'?0:1,Number(f.get('sort_order'))||0).run();await audit(env,a.user,'journey_created','journey',r.meta.last_row_id);return json({ok:true,id:r.meta.last_row_id},201);}
 if(p==='/api/admin/audit'&&m==='GET'){const a=await requireUser(request,env);if(a.error)return a.error;if(a.user.role!=='owner')return json({ok:false,error:'Owner only'},403);const r=await env.DB.prepare(`SELECT l.*,u.display_name,u.login_id FROM audit_log l LEFT JOIN admin_users u ON u.id=l.admin_user_id ORDER BY l.id DESC LIMIT 250`).all();return json({ok:true,audit:r.results||[]});}
 return null;
}
export default {async fetch(request,env){const u=new URL(request.url),p=u.pathname,m=request.method;try{
 const ar=await adminRoutes(request,env,u,p,m);if(ar)return ar;
 if(p==='/api/health')return json({ok:true,app:'SS Collections by SunShah',environment:'uat',version:'4.3.2',d1:!!env.DB,r2:!!env.FILES,secure_admin:true});
 if(p==='/api/categories')return json({ok:true,categories:CATEGORIES});
 if(p==='/api/products'&&m==='GET'){await releaseExpired(env);const r=await env.DB.prepare(productSelect()+' ORDER BY p.featured DESC,p.id DESC').all();return json({ok:true,products:(r.results||[]).map(x=>({...x,image_url:x.primary_r2_key?'/media/'+x.primary_r2_key.split('/').map(encodeURIComponent).join('/'):(x.primary_asset_url||'')}))});}
 if(p.startsWith('/api/products/')&&m==='GET'){const key=decodeURIComponent(p.slice('/api/products/'.length));const product=await env.DB.prepare('SELECT * FROM products WHERE CAST(id AS TEXT)=? OR code=?').bind(key,key).first();if(!product)return json({ok:false,error:'Product not found'},404);const mr=await env.DB.prepare('SELECT * FROM product_media WHERE product_id=? ORDER BY is_primary DESC,sort_order,id').bind(product.id).all();return json({ok:true,product:{...product,media:(mr.results||[]).map(x=>({...x,url:mediaUrl(x)}))}});}
 if(p==='/api/creations'&&m==='GET'){const r=await env.DB.prepare(`SELECT c.*, (SELECT r2_key FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_r2_key,(SELECT asset_url FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_asset_url FROM creations c ORDER BY id DESC`).all();return json({ok:true,creations:(r.results||[]).map(x=>({...x,image_url:x.primary_r2_key?'/media/'+x.primary_r2_key.split('/').map(encodeURIComponent).join('/'):(x.primary_asset_url||'')}))});}
 if(p==='/api/events'&&m==='GET'){const r=await env.DB.prepare('SELECT * FROM events ORDER BY event_date,id DESC').all();return json({ok:true,events:r.results||[]});}
 if(p==='/api/journey'&&m==='GET'){const r=await env.DB.prepare('SELECT * FROM handmade_journey WHERE is_published=1 ORDER BY sort_order,id DESC').all();return json({ok:true,journey:(r.results||[]).map(x=>({...x,url:x.r2_key?'/media/'+x.r2_key.split('/').map(encodeURIComponent).join('/'):x.external_url}))});}
 if(p==='/api/reviews'&&m==='GET'){const productId=u.searchParams.get('product_id');const q=productId?env.DB.prepare('SELECT * FROM reviews WHERE is_approved=1 AND product_id=? ORDER BY id DESC').bind(productId):env.DB.prepare('SELECT * FROM reviews WHERE is_approved=1 ORDER BY id DESC LIMIT 100');const r=await q.all();return json({ok:true,reviews:r.results||[]});}
 if(p==='/api/reviews'&&m==='POST'){const b=await requestJson(request);const rating=Number(b.rating);if(!(rating>=1&&rating<=5))return json({ok:false,error:'Rating from 1 to 5 is required'},400);await env.DB.prepare('INSERT INTO reviews(product_id,order_id,customer_name,rating,feedback,service_rating,is_approved) VALUES(?,?,?,?,?,?,0)').bind(b.product_id||null,b.order_id||null,b.customer_name||'Customer',rating,b.feedback||'',b.service_rating||null).run();return json({ok:true,message:'Feedback received and awaiting approval'},201);}
 if(p==='/api/orders'&&m==='POST'){await releaseExpired(env);const b=await requestJson(request);if(!b.customer_name||!b.whatsapp||!Array.isArray(b.product_ids)||!b.product_ids.length)return json({ok:false,error:'customer_name, whatsapp and product_ids are required'},400);const ids=[...new Set(b.product_ids.map(Number).filter(Number.isFinite))];const q=ids.map(()=>'?').join(',');const pr=await env.DB.prepare(`SELECT * FROM products WHERE id IN (${q})`).bind(...ids).all();if((pr.results||[]).length!==ids.length)return json({ok:false,error:'One or more products were not found'},404);if(pr.results.some(x=>x.status!=='available'))return json({ok:false,error:'One or more unique products are no longer available'},409);const hours=Math.min(168,Math.max(1,Number((await env.DB.prepare("SELECT value FROM settings WHERE key='reservation_hours'").first())?.value||24)));const no=orderNo(),due=new Date(Date.now()+hours*3600000).toISOString(),amount=pr.results.reduce((s,x)=>s+discounted(x),0);await env.DB.prepare(`INSERT INTO orders(order_no,customer_name,whatsapp,email,address,city,amount_pkr,payment_method,payment_due_at,payment_reference,payment_status,order_status) VALUES(?,?,?,?,?,?,?,?,?,?,'pending','reserved')`).bind(no,b.customer_name,b.whatsapp,b.email||'',b.address||'',b.city||'',amount,b.payment_method||'bank',due,no).run();const order=await env.DB.prepare('SELECT id FROM orders WHERE order_no=?').bind(no).first();for(const x of pr.results){await env.DB.prepare('INSERT INTO order_items(order_id,product_id,unit_price_pkr,product_snapshot_name,product_snapshot_code) VALUES(?,?,?,?,?)').bind(order.id,x.id,discounted(x),x.name,x.code).run();const upd=await env.DB.prepare("UPDATE products SET status='reserved',reserved_order_no=?,reserved_until=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='available'").bind(no,due,x.id).run();if(!upd.meta?.changes)throw new Error('Reservation conflict');}const first=pr.results[0],media=await env.DB.prepare('SELECT r2_key,asset_url FROM product_media WHERE product_id=? ORDER BY is_primary DESC,sort_order,id LIMIT 1').bind(first.id).first();const pic=media?.r2_key?'/media/'+media.r2_key.split('/').map(encodeURIComponent).join('/'):(media?.asset_url||'');return json({ok:true,order_no:no,amount_pkr:amount,payment_due_at:due,payment_reference:no,product_picture:pic,whatsapp_message:`SS Collections by SunShah: Order ${no} received. Amount PKR ${amount.toLocaleString('en-PK')}. Payment is due by ${new Date(due).toLocaleString('en-PK',{timeZone:'Asia/Karachi'})}. Please quote ${no} as your payment reference. If payment is not received by the due date, the reservation may be revoked and the unique product may be made available to another customer.`},201);}
 if(p.startsWith('/api/orders/')&&m==='GET'){await releaseExpired(env);const no=decodeURIComponent(p.slice('/api/orders/'.length));const o=await env.DB.prepare('SELECT * FROM orders WHERE order_no=?').bind(no).first();if(!o)return json({ok:false,error:'Order not found'},404);const ir=await env.DB.prepare('SELECT oi.*,p.status product_status FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=?').bind(o.id).all();return json({ok:true,order:{...o,items:ir.results||[]}});}
 if(p.startsWith('/media/')&&m==='GET'){const key=decodeURIComponent(p.slice('/media/'.length));if(/^(orders|returns|payments)\//.test(key)){const a=await requireUser(request,env);if(a.error)return a.error;}const obj=await env.FILES.get(key);if(!obj)return new Response('Not found',{status:404});const headers=new Headers();obj.writeHttpMetadata(headers);headers.set('etag',obj.httpEtag);headers.set('cache-control','private, max-age=3600');return new Response(obj.body,{headers});}
 if(p.startsWith('/api/'))return json({ok:false,error:'API route not found'},404);
 return env.ASSETS.fetch(request);
 }catch(e){console.error(JSON.stringify({event:'request_error',path:p,error:String(e?.message||e)}));return json({ok:false,error:'UAT API error',detail:String(e?.message||e),path:p},500)}} ,async scheduled(controller,env,ctx){ctx.waitUntil(releaseExpired(env));}};
