const CATEGORIES=['Bags','Dresses','Jewellery','Hair Accessories','Travel Bags','Winter Collection','Summer Collection','Wedding','Home Décor','Shoes','Other'];
const PREFIX={Bags:'BAG',Dresses:'DRS',Jewellery:'JWL','Hair Accessories':'HAR','Travel Bags':'TRV','Winter Collection':'WIN','Summer Collection':'SUM',Wedding:'WED','Home Décor':'HOM',Shoes:'SHO',Other:'OTH'};
async function nextCode(env,table,category){const pre=PREFIX[category]||'OTH';const r=await env.DB.prepare(`SELECT code FROM ${table} WHERE code LIKE ? ORDER BY CAST(substr(code,5) AS INTEGER) DESC LIMIT 1`).bind(pre+'-%').first();const n=r?Number(String(r.code).split('-').pop())+1:1;return pre+'-'+String(n).padStart(5,'0')}
const SESSION_COOKIE='ss_admin_session';
const SESSION_HOURS=12;
const PBKDF2_ITERATIONS=10000;
function json(data,status=200,extra={}){const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extra});return new Response(JSON.stringify(data),{status,headers:h})}
async function requestJson(request){try{return await request.json()}catch{return {}}}
function hex(bytes){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function fromHex(s){const a=new Uint8Array(s.length/2);for(let i=0;i<a.length;i++)a[i]=parseInt(s.slice(i*2,i*2+2),16);return a}
async function sha256(s){const b=typeof s==='string'?new TextEncoder().encode(s):s;return hex(await crypto.subtle.digest('SHA-256',b))}
async function passwordHash(password,saltHex){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:fromHex(saltHex),iterations:PBKDF2_ITERATIONS},key,256);return hex(bits)}
function randomHex(n=32){const a=new Uint8Array(n);crypto.getRandomValues(a);return hex(a)}
function secureEqualHex(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;const x=fromHex(a),y=fromHex(b);let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0}
function validMutationOrigin(request){const origin=request.headers.get('origin');if(!origin)return true;return origin===new URL(request.url).origin}
function cookies(request){const out={};for(const p of (request.headers.get('cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
function sessionCookie(token,maxAge=SESSION_HOURS*3600){return `${SESSION_COOKIE}=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`}
function clearCookie(){return `${SESSION_COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`}
function perms(user){try{return JSON.parse(user.permissions_json||'{}')}catch{return {}}}
function can(user,permission){if(!user)return false;if(user.role==='owner')return true;const p=perms(user);return p.all===true||p[permission]===true||Array.isArray(p)&&p.includes(permission)}
async function currentUser(request,env){const token=cookies(request)[SESSION_COOKIE];if(!token)return null;const th=await sha256(token);const user=await env.DB.prepare(`SELECT u.* FROM admin_sessions s JOIN admin_users u ON u.id=s.admin_user_id WHERE s.token_hash=? AND s.expires_at>CURRENT_TIMESTAMP AND u.is_active=1`).bind(th).first();return user||null}
async function requireUser(request,env,permission){const u=await currentUser(request,env);if(!u)return {error:json({ok:false,error:'Authentication required'},401)};if(permission&&!can(u,permission))return {error:json({ok:false,error:'Permission denied'},403)};return {user:u}}
async function audit(env,user,action,type,id,details={}){await env.DB.prepare('INSERT INTO audit_log(admin_user_id,action,entity_type,entity_id,details_json) VALUES(?,?,?,?,?)').bind(user?.id||null,action,type||null,id==null?null:String(id),JSON.stringify(details)).run()}
function mediaUrl(row){if(row?.r2_key)return '/media/'+row.r2_key.split('/').map(encodeURIComponent).join('/');return row?.asset_url||''}
async function releaseExpired(env){const now=new Date().toISOString();const expired=await env.DB.prepare("SELECT order_no FROM orders WHERE payment_status='pending' AND order_status IN ('reserved','payment_pending') AND payment_due_at IS NOT NULL AND payment_due_at < ?").bind(now).all();for(const o of expired.results||[]){await env.DB.batch([env.DB.prepare("UPDATE products SET status='available',reserved_order_no=NULL,reserved_until=NULL,updated_at=CURRENT_TIMESTAMP WHERE reserved_order_no=? AND status='reserved'").bind(o.order_no),env.DB.prepare("UPDATE orders SET order_status='revoked',updated_at=CURRENT_TIMESTAMP WHERE order_no=?").bind(o.order_no)]);}return expired.results?.length||0}
function orderNo(){const d=new Date();return `SS-${d.getUTCFullYear()}-${String(Date.now()).slice(-6)}`}
function discounted(p){const price=Number(p.price_pkr)||0,v=Number(p.discount_value)||0;return p.discount_type==='fixed'?Math.max(0,price-v):Math.round(price*(1-v/100))}
function fileKind(file){const t=(file.type||'').toLowerCase();return t.startsWith('video/')?'video':'image'}
async function putFile(env,file,prefix){if(!(file instanceof File)||!file.size)throw new Error('File required');const kind=fileKind(file);const max=kind==='video'?20*1024*1024:8*1024*1024;if(file.size>max)throw new Error(`${kind==='video'?'Video':'Image'} exceeds UAT limit (${kind==='video'?'20 MB':'8 MB'})`);const ext=(file.name.split('.').pop()|| (kind==='video'?'mp4':'jpg')).replace(/[^a-zA-Z0-9]/g,'').slice(0,8);const key=`${prefix}/${Date.now()}-${crypto.randomUUID()}.${ext}`;await env.FILES.put(key,file.stream(),{httpMetadata:{contentType:file.type||'application/octet-stream'},customMetadata:{originalName:file.name}});return {key,kind,size:file.size}}
async function parseForm(request){return await request.formData()}
function productSelect(){return `SELECT p.*, (SELECT r2_key FROM product_media pm WHERE pm.product_id=p.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_r2_key,(SELECT asset_url FROM product_media pm WHERE pm.product_id=p.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_asset_url FROM products p`}
async function createProductRecord(env,user,data){
 const name=String(data.name||'').trim(),category=String(data.category||'').trim();
 if(!name||!CATEGORIES.includes(category))return {error:json({ok:false,error:'Name and valid category are required'},400)};
 const code=await nextCode(env,'products',category);
 const price=Math.max(0,Number(data.price_pkr)||0),discount=Math.min(100,Math.max(0,Number(data.discount_value)||0)),status=String(data.status||'available');
 const featured=(data.featured===true||data.featured===1||data.featured==='1'||data.featured==='true')?1:0;
 const ins=await env.DB.prepare(`INSERT INTO products(code,name,category,description,price_pkr,discount_type,discount_value,status,unique_piece,featured) VALUES(?,?,?,?,?,'percent',?,?,1,?)`).bind(code,name,category,String(data.description||''),price,discount,status,featured).run();
 const id=ins.meta.last_row_id;
 await audit(env,user,'product_created','product',id,{code,name,media:0});
 return {id,code,name};
}
async function adminRoutes(request,env,u,p,m){
 if(p.startsWith('/api/admin/')&&['POST','PATCH','PUT','DELETE'].includes(m)&&!validMutationOrigin(request))return json({ok:false,error:'Invalid request origin'},403);
 if(p==='/api/admin/login'&&m==='POST'){const b=await requestJson(request);const user=await env.DB.prepare('SELECT * FROM admin_users WHERE login_id=? AND is_active=1').bind(String(b.login_id||'').trim()).first();if(!user||!user.password_hash||!user.password_salt)return json({ok:false,error:'Invalid login ID or password'},401);const ph=await passwordHash(String(b.password||''),user.password_salt);if(!secureEqualHex(ph,user.password_hash))return json({ok:false,error:'Invalid login ID or password'},401);const token=randomHex(32),th=await sha256(token),exp=new Date(Date.now()+SESSION_HOURS*3600000).toISOString();await env.DB.prepare('INSERT INTO admin_sessions(admin_user_id,token_hash,expires_at) VALUES(?,?,?)').bind(user.id,th,exp).run();await audit(env,user,'login','admin_user',user.id);return json({ok:true,user:{id:user.id,login_id:user.login_id,display_name:user.display_name,role:user.role,permissions:perms(user)}},200,{'set-cookie':sessionCookie(token)});}
 if(p==='/api/admin/logout'&&m==='POST'){const token=cookies(request)[SESSION_COOKIE];if(token)await env.DB.prepare('DELETE FROM admin_sessions WHERE token_hash=?').bind(await sha256(token)).run();return json({ok:true},200,{'set-cookie':clearCookie()});}
 if(p==='/api/admin/me'&&m==='GET'){const a=await requireUser(request,env);if(a.error)return a.error;return json({ok:true,user:{id:a.user.id,login_id:a.user.login_id,display_name:a.user.display_name,role:a.user.role,permissions:perms(a.user)}});}
 if(p==='/api/admin/password'&&m==='POST'){const a=await requireUser(request,env);if(a.error)return a.error;const b=await requestJson(request);if(String(b.new_password||'').length<10)return json({ok:false,error:'New password must be at least 10 characters'},400);const salt=randomHex(16),hash=await passwordHash(b.new_password,salt);await env.DB.prepare('UPDATE admin_users SET password_hash=?,password_salt=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(hash,salt,a.user.id).run();await env.DB.prepare('DELETE FROM admin_sessions WHERE admin_user_id=?').bind(a.user.id).run();await audit(env,a.user,'password_changed','admin_user',a.user.id);return json({ok:true,message:'Password changed. Please login again.'},200,{'set-cookie':clearCookie()});}
 if(p==='/api/admin/summary'&&m==='GET'){const a=await requireUser(request,env);if(a.error)return a.error;const [products,orders,returns,users]=await Promise.all([env.DB.prepare("SELECT COUNT(*) n, SUM(status='available') available, SUM(status='reserved') reserved, SUM(status='sold_locked') sold FROM products").first(),env.DB.prepare("SELECT COUNT(*) n, SUM(payment_status='pending') payment_pending, SUM(order_status='dispatched') dispatched FROM orders").first(),env.DB.prepare("SELECT COUNT(*) n, SUM(status NOT IN ('refunded','rejected')) open FROM returns").first(),env.DB.prepare("SELECT COUNT(*) n FROM admin_users WHERE is_active=1").first()]);return json({ok:true,summary:{products,orders,returns,active_users:users?.n||0}});}
 if(p==='/api/admin/products'&&m==='GET'){const a=await requireUser(request,env,'products');if(a.error)return a.error;const r=await env.DB.prepare(productSelect()+' ORDER BY p.id DESC').all();return json({ok:true,products:(r.results||[]).map(x=>({...x,image_url:x.primary_r2_key?'/media/'+x.primary_r2_key.split('/').map(encodeURIComponent).join('/'):(x.primary_asset_url||'')}))});}
 if((p==='/api/admin/products'||p==='/api/admin/products/create'||p==='/api/admin/product-save')&&m==='POST'){const a=await requireUser(request,env,'products');if(a.error)return a.error;let data={},files=[];const ct=(request.headers.get('content-type')||'').toLowerCase();if(ct.includes('application/json'))data=await requestJson(request);else{const f=await parseForm(request);data=Object.fromEntries(f.entries());files=f.getAll('media').filter(x=>x instanceof File&&x.size);}const out=await createProductRecord(env,a.user,data);if(out.error)return out.error;let sort=0;for(const file of files){const up=await putFile(env,file,`products/${out.code}`);await env.DB.prepare('INSERT INTO product_media(product_id,media_type,r2_key,is_primary,sort_order) VALUES(?,?,?,?,?)').bind(out.id,up.kind,up.key,sort===0?1:0,sort++).run();}if(files.length)await audit(env,a.user,'product_media_added','product',out.id,{count:files.length});return json({ok:true,id:out.id,code:out.code,media_count:files.length,message:'Product saved successfully.'},201);}
 if(p.match(/^\/api\/admin\/products\/\d+$/)&&m==='PATCH'){const a=await requireUser(request,env,'products');if(a.error)return a.error;const id=Number(p.split('/').pop()),b=await requestJson(request);const old=await env.DB.prepare('SELECT * FROM products WHERE id=?').bind(id).first();if(!old)return json({ok:false,error:'Product not found'},404);const name=String(b.name??old.name),category=String(b.category??old.category),description=String(b.description??old.description??''),price=Math.max(0,Number(b.price_pkr??old.price_pkr)||0),discount=Math.max(0,Number(b.discount_value??old.discount_value)||0),featured=b.featured==null?old.featured:(b.featured?1:0);let status=String(b.status??old.status);if(old.status==='sold_locked'&&status!=='sold_locked'&&a.user.role!=='owner')return json({ok:false,error:'Only Owner may change a Sold & Locked item'},403);await env.DB.prepare('UPDATE products SET name=?,category=?,description=?,price_pkr=?,discount_value=?,status=?,featured=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(name,category,description,price,discount,status,featured,id).run();await audit(env,a.user,'product_updated','product',id,{before:{price:old.price_pkr,status:old.status},after:{price,status}});return json({ok:true});}
 if(p.match(/^\/api\/admin\/products\/\d+\/media$/)&&m==='POST'){const a=await requireUser(request,env,'products');if(a.error)return a.error;const id=Number(p.split('/')[4]),prod=await env.DB.prepare('SELECT * FROM products WHERE id=?').bind(id).first();if(!prod)return json({ok:false,error:'Product not found'},404);const f=await parseForm(request),files=f.getAll('media').filter(x=>x instanceof File&&x.size);const c=await env.DB.prepare('SELECT COUNT(*) n FROM product_media WHERE product_id=?').bind(id).first();let sort=Number(c?.n||0);for(const file of files){const up=await putFile(env,file,`products/${prod.code}`);await env.DB.prepare('INSERT INTO product_media(product_id,media_type,r2_key,is_primary,sort_order) VALUES(?,?,?,?,?)').bind(id,up.kind,up.key,sort===0?1:0,sort++).run();}await audit(env,a.user,'product_media_added','product',id,{count:files.length});return json({ok:true,count:files.length});}
 if(p==='/api/admin/users'&&m==='GET'){const a=await requireUser(request,env);if(a.error)return a.error;if(a.user.role!=='owner')return json({ok:false,error:'Owner only'},403);const r=await env.DB.prepare('SELECT id,login_id,display_name,role,permissions_json,is_active,created_at FROM admin_users ORDER BY id').all();return json({ok:true,users:(r.results||[]).map(x=>({...x,permissions:perms(x)}))});}
 if(p==='/api/admin/users'&&m==='POST'){const a=await requireUser(request,env);if(a.error)return a.error;if(a.user.role!=='owner')return json({ok:false,error:'Owner only'},403);const b=await requestJson(request),login=String(b.login_id||'').trim();if(!login||String(b.password||'').length<10)return json({ok:false,error:'Login ID and password of at least 10 characters required'},400);const salt=randomHex(16),hash=await passwordHash(b.password,salt),role=['admin','agent'].includes(b.role)?b.role:'agent',pj=JSON.stringify(b.permissions||{});const r=await env.DB.prepare('INSERT INTO admin_users(login_id,display_name,password_hash,password_salt,role,permissions_json,is_active) VALUES(?,?,?,?,?,?,1)').bind(login,String(b.display_name||login),hash,salt,role,pj).run();await audit(env,a.user,'user_created','admin_user',r.meta.last_row_id,{login,role,permissions:b.permissions||{}});return json({ok:true,id:r.meta.last_row_id},201);}
 if(p.match(/^\/api\/admin\/users\/\d+$/)&&m==='PATCH'){const a=await requireUser(request,env);if(a.error)return a.error;if(a.user.role!=='owner')return json({ok:false,error:'Owner only'},403);const id=Number(p.split('/').pop());if(id===a.user.id)return json({ok:false,error:'Owner cannot disable own account here'},400);const b=await requestJson(request);const cur=await env.DB.prepare('SELECT * FROM admin_users WHERE id=?').bind(id).first();if(!cur||cur.role==='owner')return json({ok:false,error:'Protected account'},400);const active=b.is_active==null?cur.is_active:(b.is_active?1:0),role=['admin','agent'].includes(b.role)?b.role:cur.role,pj=JSON.stringify(b.permissions??perms(cur));await env.DB.prepare('UPDATE admin_users SET is_active=?,role=?,permissions_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(active,role,pj,id).run();if(!active)await env.DB.prepare('DELETE FROM admin_sessions WHERE admin_user_id=?').bind(id).run();await audit(env,a.user,'user_updated','admin_user',id,{active,role,permissions:b.permissions??perms(cur)});return json({ok:true});}
 if(p==='/api/admin/orders'&&m==='GET'){const a=await requireUser(request,env,'orders');if(a.error)return a.error;const r=await env.DB.prepare(`SELECT o.*, GROUP_CONCAT(oi.product_snapshot_code||' - '||oi.product_snapshot_name,' | ') items FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id GROUP BY o.id ORDER BY o.id DESC LIMIT 200`).all();return json({ok:true,orders:r.results||[]});}
 if(p.match(/^\/api\/admin\/orders\/\d+$/)&&m==='PATCH'){const a=await requireUser(request,env,'orders');if(a.error)return a.error;const id=Number(p.split('/').pop()),b=await requestJson(request),o=await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(id).first();if(!o)return json({ok:false,error:'Order not found'},404);if(b.action==='confirm_payment'){const days=Math.min(60,Math.max(1,Number(b.dispatch_working_days)||3));await env.DB.batch([env.DB.prepare("UPDATE orders SET payment_status='confirmed',order_status='paid',dispatch_working_days=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(days,id),env.DB.prepare("UPDATE products SET status='sold_locked',reserved_until=NULL,updated_at=CURRENT_TIMESTAMP WHERE reserved_order_no=?").bind(o.order_no)]);await audit(env,a.user,'payment_confirmed','order',id,{order_no:o.order_no,dispatch_working_days:days});return json({ok:true,dispatch_working_days:days,whatsapp_message:`Your payment for Order No. ${o.order_no} has been received by SS Collections. Your order is expected to be dispatched within ${days} working day${days===1?'':'s'}. Once dispatched, your tracking ID will be shared with you via WhatsApp.\n\nRegards,\nSS Collections by SunShah`});}if(b.action==='dispatch'){await env.DB.prepare("UPDATE orders SET order_status='dispatched',courier_name=?,tracking_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(String(b.courier_name||''),String(b.tracking_id||''),id).run();await audit(env,a.user,'order_dispatched','order',id,{courier:b.courier_name,tracking:b.tracking_id});return json({ok:true});}if(b.action==='status'){await env.DB.prepare('UPDATE orders SET order_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(String(b.order_status||o.order_status),id).run();await audit(env,a.user,'order_status_updated','order',id,{status:b.order_status});return json({ok:true});}return json({ok:false,error:'Unknown order action'},400);}
 if(p.match(/^\/api\/admin\/orders\/\d+\/media$/)&&m==='POST'){const a=await requireUser(request,env,'orders');if(a.error)return a.error;const id=Number(p.split('/')[4]),f=await parseForm(request),kind=String(f.get('media_type')||'product_before_dispatch'),files=f.getAll('media').filter(x=>x instanceof File&&x.size);for(const file of files){const up=await putFile(env,file,`orders/${id}/${kind}`);await env.DB.prepare('INSERT INTO order_media(order_id,media_type,file_type,r2_key,caption) VALUES(?,?,?,?,?)').bind(id,kind,up.kind,up.key,String(f.get('caption')||'')).run();}await audit(env,a.user,'order_media_added','order',id,{kind,count:files.length});return json({ok:true,count:files.length});}
 if(p==='/api/admin/events'&&m==='GET'){const a=await requireUser(request,env,'events');if(a.error)return a.error;const r=await env.DB.prepare('SELECT * FROM events ORDER BY event_date DESC,id DESC').all();return json({ok:true,events:r.results||[]});}
 if(p==='/api/admin/events'&&m==='POST'){const a=await requireUser(request,env,'events');if(a.error)return a.error;const f=await parseForm(request);let mediaKey=null;const file=f.get('media');if(file instanceof File&&file.size)mediaKey=(await putFile(env,file,'events')).key;const r=await env.DB.prepare('INSERT INTO events(title,city,venue,stall_no,event_date,timing,maps_url,media_r2_key,details,status) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(String(f.get('title')||''),String(f.get('city')||''),String(f.get('venue')||''),String(f.get('stall_no')||''),String(f.get('event_date')||''),String(f.get('timing')||''),String(f.get('maps_url')||''),mediaKey,String(f.get('details')||''),String(f.get('status')||'upcoming')).run();await audit(env,a.user,'event_created','event',r.meta.last_row_id);return json({ok:true,id:r.meta.last_row_id},201);}
 if(p==='/api/admin/creations'&&m==='GET'){const a=await requireUser(request,env,'creations');if(a.error)return a.error;const r=await env.DB.prepare('SELECT * FROM creations ORDER BY id DESC').all();return json({ok:true,creations:r.results||[]});}
 if(p==='/api/admin/creations'&&m==='POST'){const a=await requireUser(request,env,'creations');if(a.error)return a.error;const f=await parseForm(request),category=String(f.get('category')||'Other');if(!CATEGORIES.includes(category))return json({ok:false,error:'Valid category is required'},400);const code=await nextCode(env,'creations',category),title=String(f.get('title')||'').trim(),status=String(f.get('status')||'Past Collection'),season=String(f.get('season')||'All Season'),price=Math.max(0,Number(f.get('price_pkr'))||0);if(!title)return json({ok:false,error:'Title is required'},400);if(status==='Available Now'&&price<=0)return json({ok:false,error:'Price is required when a creation is Available Now and will be shown in Shop'},400);const r=await env.DB.prepare('INSERT INTO creations(code,title,category,status,season,note,custom_possible) VALUES(?,?,?,?,?,?,?)').bind(code,title,category,status,season,String(f.get('note')||''),f.get('custom_possible')==='0'?0:1).run();const id=r.meta.last_row_id,files=f.getAll('media').filter(x=>x instanceof File&&x.size);let sort=0,uploaded=[];for(const file of files){const up=await putFile(env,file,`creations/${code}`);uploaded.push(up);await env.DB.prepare('INSERT INTO creation_media(creation_id,media_type,r2_key,is_primary,sort_order) VALUES(?,?,?,?,?)').bind(id,up.kind,up.key,sort===0?1:0,sort++).run();}let product_id=null;if(status==='Available Now'){const ex=await env.DB.prepare('SELECT id FROM products WHERE code=?').bind(code).first();if(ex){product_id=ex.id;await env.DB.prepare("UPDATE products SET name=?,category=?,description=?,price_pkr=?,status='available',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(title,category,String(f.get('note')||''),price,product_id).run();}else{const pr=await env.DB.prepare(`INSERT INTO products(code,name,category,description,price_pkr,discount_type,discount_value,status,unique_piece,featured) VALUES(?,?,?,?,?,'percent',0,'available',1,0)`).bind(code,title,category,String(f.get('note')||''),price).run();product_id=pr.meta.last_row_id;}for(let i=0;i<uploaded.length;i++)await env.DB.prepare('INSERT OR IGNORE INTO product_media(product_id,media_type,r2_key,is_primary,sort_order) VALUES(?,?,?,?,?)').bind(product_id,uploaded[i].kind,uploaded[i].key,i===0?1:0,i).run();}await audit(env,a.user,'creation_created','creation',id,{code,media:files.length,status,shop_product_id:product_id});return json({ok:true,id,code,shop_product_id:product_id},201);}
 if(p==='/api/admin/journey'&&m==='GET'){const a=await requireUser(request,env,'journey');if(a.error)return a.error;const r=await env.DB.prepare('SELECT * FROM handmade_journey ORDER BY id DESC').all();return json({ok:true,journey:r.results||[]});}
 if(p==='/api/admin/journey'&&m==='POST'){const a=await requireUser(request,env,'journey');if(a.error)return a.error;const f=await parseForm(request),file=f.get('media');let r2=null,mediaType='video';if(file instanceof File&&file.size){const up=await putFile(env,file,'journey');r2=up.key;mediaType=up.kind}const r=await env.DB.prepare('INSERT INTO handmade_journey(title,description,stage,media_type,r2_key,external_url,is_published,sort_order) VALUES(?,?,?,?,?,?,?,?)').bind(String(f.get('title')||''),String(f.get('description')||''),String(f.get('stage')||''),mediaType,r2,String(f.get('external_url')||''),f.get('is_published')==='0'?0:1,Number(f.get('sort_order'))||0).run();await audit(env,a.user,'journey_created','journey',r.meta.last_row_id);return json({ok:true,id:r.meta.last_row_id},201);}
 if(p==='/api/admin/audit'&&m==='GET'){const a=await requireUser(request,env);if(a.error)return a.error;if(a.user.role!=='owner')return json({ok:false,error:'Owner only'},403);const r=await env.DB.prepare(`SELECT l.*,u.display_name,u.login_id FROM audit_log l LEFT JOIN admin_users u ON u.id=l.admin_user_id ORDER BY l.id DESC LIMIT 250`).all();return json({ok:true,audit:r.results||[]});}
 return null;
}
export default {async fetch(request,env){const u=new URL(request.url),p=u.pathname.length>1?u.pathname.replace(/\/+$/,''):u.pathname,m=request.method;try{
 const ar=await adminRoutes(request,env,u,p,m);if(ar)return ar;
 if(p==='/api/health')return json({ok:true,app:'SS Collections by SunShah',environment:'uat',version:'4.4.4',d1:!!env.DB,r2:!!env.FILES,secure_admin:true});
 if(p==='/api/categories')return json({ok:true,categories:CATEGORIES});
 if(p==='/api/products'&&m==='GET'){await releaseExpired(env);const r=await env.DB.prepare(productSelect()+' ORDER BY p.featured DESC,p.id DESC').all();return json({ok:true,products:(r.results||[]).map(x=>({...x,image_url:x.primary_r2_key?'/media/'+x.primary_r2_key.split('/').map(encodeURIComponent).join('/'):(x.primary_asset_url||'')}))});}
 if(p.startsWith('/api/products/')&&m==='GET'){const key=decodeURIComponent(p.slice('/api/products/'.length));const product=await env.DB.prepare('SELECT * FROM products WHERE CAST(id AS TEXT)=? OR code=?').bind(key,key).first();if(!product)return json({ok:false,error:'Product not found'},404);const mr=await env.DB.prepare('SELECT * FROM product_media WHERE product_id=? ORDER BY is_primary DESC,sort_order,id').bind(product.id).all();return json({ok:true,product:{...product,media:(mr.results||[]).map(x=>({...x,url:mediaUrl(x)}))}});}
 if(p==='/api/creations'&&m==='GET'){const r=await env.DB.prepare(`SELECT c.*, (SELECT r2_key FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_r2_key,(SELECT asset_url FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_asset_url FROM creations c ORDER BY id DESC`).all();return json({ok:true,creations:(r.results||[]).map(x=>({...x,image_url:x.primary_r2_key?'/media/'+x.primary_r2_key.split('/').map(encodeURIComponent).join('/'):(x.primary_asset_url||'')}))});}
 if(p.startsWith('/api/creations/')&&m==='GET'){const code=decodeURIComponent(p.slice('/api/creations/'.length)).toUpperCase();const c=await env.DB.prepare(`SELECT c.*, (SELECT r2_key FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_r2_key,(SELECT asset_url FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_asset_url FROM creations c WHERE c.code=?`).bind(code).first();if(!c)return json({ok:false,error:'Creation not found'},404);const mr=await env.DB.prepare('SELECT * FROM creation_media WHERE creation_id=? ORDER BY is_primary DESC,sort_order,id').bind(c.id).all();return json({ok:true,creation:{...c,image_url:c.primary_r2_key?'/media/'+c.primary_r2_key.split('/').map(encodeURIComponent).join('/'):(c.primary_asset_url||''),media:(mr.results||[]).map(x=>({...x,url:mediaUrl(x)}))}});}
 if(p==='/api/events'&&m==='GET'){const r=await env.DB.prepare(`SELECT e.*,CASE WHEN e.media_r2_key IS NOT NULL THEN '/media/'||e.media_r2_key ELSE e.asset_url END asset_url,(SELECT COUNT(*) FROM event_interest i WHERE i.event_id=e.id AND i.choice='yes') interested_yes,(SELECT COUNT(*) FROM event_interest i WHERE i.event_id=e.id AND i.choice='no') interested_no,(SELECT COUNT(*) FROM event_interest i WHERE i.event_id=e.id AND i.choice='not_available') interested_not_available FROM events e ORDER BY e.event_date,e.id DESC`).all();return json({ok:true,events:r.results||[]});}
 if(p==='/api/journey'&&m==='GET'){const r=await env.DB.prepare('SELECT * FROM handmade_journey WHERE is_published=1 ORDER BY sort_order,id DESC').all();return json({ok:true,journey:(r.results||[]).map(x=>({...x,url:x.r2_key?'/media/'+x.r2_key.split('/').map(encodeURIComponent).join('/'):x.external_url}))});}
 if(p==='/api/reviews'&&m==='GET'){const productId=u.searchParams.get('product_id');const q=productId?env.DB.prepare('SELECT * FROM reviews WHERE is_approved=1 AND product_id=? ORDER BY id DESC').bind(productId):env.DB.prepare('SELECT * FROM reviews WHERE is_approved=1 ORDER BY id DESC LIMIT 100');const r=await q.all();return json({ok:true,reviews:r.results||[]});}
 if(p==='/api/reviews'&&m==='POST'){const b=await requestJson(request);const rating=Number(b.rating);if(!(rating>=1&&rating<=5))return json({ok:false,error:'Rating from 1 to 5 is required'},400);await env.DB.prepare('INSERT INTO reviews(product_id,order_id,customer_name,rating,feedback,service_rating,is_approved) VALUES(?,?,?,?,?,?,0)').bind(b.product_id||null,b.order_id||null,b.customer_name||'Customer',rating,b.feedback||'',b.service_rating||null).run();return json({ok:true,message:'Feedback received and awaiting approval'},201);}
 if(p==='/api/orders'&&m==='POST'){await releaseExpired(env);const b=await requestJson(request);if(!b.customer_name||!b.whatsapp||!Array.isArray(b.product_ids)||!b.product_ids.length)return json({ok:false,error:'customer_name, whatsapp and product_ids are required'},400);const ids=[...new Set(b.product_ids.map(Number).filter(Number.isFinite))];const q=ids.map(()=>'?').join(',');const pr=await env.DB.prepare(`SELECT * FROM products WHERE id IN (${q})`).bind(...ids).all();if((pr.results||[]).length!==ids.length)return json({ok:false,error:'One or more products were not found'},404);if(pr.results.some(x=>x.status!=='available'))return json({ok:false,error:'One or more unique products are no longer available'},409);const hours=Math.min(168,Math.max(1,Number((await env.DB.prepare("SELECT value FROM settings WHERE key='reservation_hours'").first())?.value||24)));const no=orderNo(),due=new Date(Date.now()+hours*3600000).toISOString(),amount=pr.results.reduce((s,x)=>s+discounted(x),0);await env.DB.prepare(`INSERT INTO orders(order_no,customer_name,whatsapp,email,address,city,amount_pkr,payment_method,payment_due_at,payment_reference,payment_status,order_status) VALUES(?,?,?,?,?,?,?,?,?,?,'pending','reserved')`).bind(no,b.customer_name,b.whatsapp,b.email||'',b.address||'',b.city||'',amount,b.payment_method||'bank',due,no).run();const order=await env.DB.prepare('SELECT id FROM orders WHERE order_no=?').bind(no).first();for(const x of pr.results){await env.DB.prepare('INSERT INTO order_items(order_id,product_id,unit_price_pkr,product_snapshot_name,product_snapshot_code) VALUES(?,?,?,?,?)').bind(order.id,x.id,discounted(x),x.name,x.code).run();const upd=await env.DB.prepare("UPDATE products SET status='reserved',reserved_order_no=?,reserved_until=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='available'").bind(no,due,x.id).run();if(!upd.meta?.changes)throw new Error('Reservation conflict');}const first=pr.results[0],media=await env.DB.prepare('SELECT r2_key,asset_url FROM product_media WHERE product_id=? ORDER BY is_primary DESC,sort_order,id LIMIT 1').bind(first.id).first();const pic=media?.r2_key?'/media/'+media.r2_key.split('/').map(encodeURIComponent).join('/'):(media?.asset_url||'');return json({ok:true,order_no:no,amount_pkr:amount,payment_due_at:due,payment_reference:no,product_picture:pic,whatsapp_message:`SS Collections by SunShah: Order ${no} received. Amount PKR ${amount.toLocaleString('en-PK')}. Payment is due by ${new Date(due).toLocaleString('en-PK',{timeZone:'Asia/Karachi'})}. Please quote ${no} as your payment reference. If payment is not received by the due date, the reservation may be revoked and the unique product may be made available to another customer.`},201);}
 if(p.startsWith('/api/orders/')&&m==='GET'){await releaseExpired(env);const no=decodeURIComponent(p.slice('/api/orders/'.length));const o=await env.DB.prepare('SELECT * FROM orders WHERE order_no=?').bind(no).first();if(!o)return json({ok:false,error:'Order not found'},404);const ir=await env.DB.prepare('SELECT oi.*,p.status product_status FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=?').bind(o.id).all();return json({ok:true,order:{...o,items:ir.results||[]}});}
 if(p.match(/^\/api\/events\/\d+\/interest$/)&&m==='POST'){const id=Number(p.split('/')[3]),b=await requestJson(request),choice=String(b.choice||'').toLowerCase().replace(/\s+/g,'_');if(!['yes','no','not_available'].includes(choice))return json({ok:false,error:'Choose yes, no or not_available'},400);const e=await env.DB.prepare('SELECT id FROM events WHERE id=?').bind(id).first();if(!e)return json({ok:false,error:'Event not found'},404);await env.DB.prepare('INSERT INTO event_interest(event_id,choice,visitor_key) VALUES(?,?,?)').bind(id,choice,String(b.visitor_key||'').slice(0,80)).run();return json({ok:true,message:'Thank you for your response.'},201);}
 if(p==='/api/custom-requests'&&m==='POST'){const f=await parseForm(request),name=String(f.get('customer_name')||'').trim(),wa=String(f.get('whatsapp')||'').trim();if(!name||!wa)return json({ok:false,error:'Name and WhatsApp are required'},400);let refKey=null;const file=f.get('media');if(file instanceof File&&file.size)refKey=(await putFile(env,file,'custom-requests')).key;const r=await env.DB.prepare('INSERT INTO custom_requests(customer_name,whatsapp,product_type,reference_code,colour_size,instructions,reference_r2_key,status) VALUES(?,?,?,?,?,?,?,\'new\')').bind(name,wa,String(f.get('product_type')||''),String(f.get('reference_code')||''),String(f.get('colour_size')||''),String(f.get('instructions')||''),refKey).run();return json({ok:true,id:r.meta.last_row_id,message:'Custom request received'},201);}
 if(p==='/api/ai/chat'&&m==='POST'){const b=await requestJson(request),action=String(b.action||'').trim(),message=String(b.message||'').trim().slice(0,1200),upper=message.toUpperCase();
  const menu=()=>json({ok:true,mode:'menu',answer:'Please choose an option below.',options:['Shop Products','My Order','Request Similar','Upcoming Events','Payment Information','Delivery & Tracking','Returns','Other Help']});
  if(action==='shop'){const pr=await env.DB.prepare(`${productSelect()} WHERE p.status='available' ORDER BY p.featured DESC,p.id DESC LIMIT 24`).all();const available=(pr.results||[]).map(x=>({kind:'product',id:x.id,code:x.code,name:x.name,category:x.category,price_pkr:x.price_pkr,discount_value:x.discount_value,status:x.status,image_url:x.primary_r2_key?'/media/'+x.primary_r2_key.split('/').map(encodeURIComponent).join('/'):(x.primary_asset_url||'')}));return json({ok:true,mode:'shop',answer:available.length?'Available products are shown below. You can also type bag, dress, jewellery, shoes, etc.':'No products are currently available to buy.',available,options:['Bags','Dresses','Jewellery','Hair Accessories','Travel Bags','Home Décor','Shoes','Wedding']});}
  if(action==='my_order'){return json({ok:true,mode:'prompt_order',answer:'Enter your SS Collections Order Number. I will show the complete order information and available actions.',options:[]});}
  if(action==='request_similar'){const cr=await env.DB.prepare(`SELECT c.*, (SELECT r2_key FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) rk,(SELECT asset_url FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) au FROM creations c WHERE c.custom_possible=1 ORDER BY c.id DESC LIMIT 30`).all();return json({ok:true,mode:'creations',answer:'Choose a design below. We will carry its exact code and picture into your Request Similar form.',creations:(cr.results||[]).map(x=>({kind:'creation',code:x.code,name:x.title,category:x.category,status:x.status,image_url:x.rk?'/media/'+x.rk.split('/').map(encodeURIComponent).join('/'):(x.au||''),custom_possible:true}))});}
  if(action==='events'){const er=await env.DB.prepare("SELECT id,title,city,venue,event_date,timing,stall_no,status FROM events WHERE event_date>=date('now') ORDER BY event_date,id LIMIT 10").all();return json({ok:true,mode:'events',answer:(er.results||[]).length?'Here are our upcoming events.':'No upcoming event is currently announced.',events:er.results||[]});}
  if(action==='payment'){return json({ok:true,mode:'info',answer:'SS Collections accepts advance payment only; COD is not available. After placing an order, use the generated Order Number as the payment reference. Payment status is confirmed only after authorised verification.',links:[{label:'Track / check an order',action:'my_order'}]});}
  if(action==='delivery'){return json({ok:true,mode:'prompt_order',answer:'Enter your Order Number to see preparation, dispatch, courier and tracking details.',options:[]});}
  if(action==='returns'){return json({ok:true,mode:'info',answer:'For a wrong item, confirmed workmanship defect or transit damage, use the Returns section. Refund processing starts after the returned item is received and verified; approved refunds are processed within 15 working days.',links:[{label:'Open Returns',href:'#returns'}]});}
  if(action==='other'){return json({ok:true,mode:'faq_menu',answer:'Choose what you would like to know.',options:['Are these handmade?','Custom orders','Discounts','No COD','Contact on WhatsApp','Handmade Journey']});}
  if(!message)return menu();
  if(message.length<=1)return menu();
  const orderMatches=[...upper.matchAll(/SS-\d{4}-\d{6}/g)].map(x=>x[0]);if(orderMatches.length){const orders=[];for(const no of [...new Set(orderMatches)]){const o=await env.DB.prepare('SELECT * FROM orders WHERE order_no=?').bind(no).first();if(o){const ir=await env.DB.prepare('SELECT product_snapshot_code code,product_snapshot_name name,unit_price_pkr FROM order_items WHERE order_id=? ORDER BY id').bind(o.id).all();orders.push({...o,items:ir.results||[]});}}if(!orders.length)return json({ok:true,mode:'order_not_found',answer:'I could not find that order number. Please check the number and try again.',options:['My Order','Other Help']});return json({ok:true,mode:'orders',answer:orders.length===1?'Here is your complete order information.':'Here are the orders I found.',orders,options:['Track Shipment','View Products','Payment Information','Request Help']});}
  const codeMatches=[...upper.matchAll(/\b(?:BAG|DRS|JWL|HAR|TRV|WIN|SUM|WED|HOM|SHO|OTH)-\d{1,5}\b/g)].map(x=>x[0]);if(codeMatches.length){const items=[];for(const code of [...new Set(codeMatches)]){const pdt=await env.DB.prepare(`${productSelect()} WHERE p.code=?`).bind(code).first();if(pdt){items.push({kind:'product',id:pdt.id,code:pdt.code,name:pdt.name,category:pdt.category,price_pkr:pdt.price_pkr,discount_value:pdt.discount_value,status:pdt.status,image_url:pdt.primary_r2_key?'/media/'+pdt.primary_r2_key.split('/').map(encodeURIComponent).join('/'):(pdt.primary_asset_url||'')});continue}const c=await env.DB.prepare(`SELECT c.*, (SELECT r2_key FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) rk,(SELECT asset_url FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) au FROM creations c WHERE c.code=?`).bind(code).first();if(c)items.push({kind:'creation',code:c.code,name:c.title,category:c.category,status:c.status,image_url:c.rk?'/media/'+c.rk.split('/').map(encodeURIComponent).join('/'):(c.au||''),custom_possible:!!c.custom_possible});}if(items.length)return json({ok:true,mode:'products',answer:'Here are the exact references you entered.',products:items,options:['Shop Products','Request Similar']});return json({ok:true,mode:'product_not_found',answer:'I could not find those product/design codes. Please check the code or choose a category.',options:['Shop Products','Request Similar']});}
  const aliases=[['Bags',['bag','bags','handbag','hand bag','beg','purse']],['Dresses',['dress','dresses','suit','suits','clothes','clothing']],['Jewellery',['jewellery','jewelry','jewel','necklace']],['Hair Accessories',['hair','paranda','hair accessory','hair accessories']],['Travel Bags',['travel bag','travel bags','trolley','laptop bag','office bag']],['Winter Collection',['winter','shawl','jacket']],['Summer Collection',['summer']],['Wedding',['wedding','bridal']],['Home Décor',['home decor','home décor','decor','wall hanging']],['Shoes',['shoe','shoes','khussa']]];let category=null;const low=message.toLowerCase();for(const [cat,words] of aliases){if(words.some(w=>low.includes(w))){category=cat;break}}if(category){const pr=await env.DB.prepare(`${productSelect()} WHERE p.category=? AND p.status='available' ORDER BY p.featured DESC,p.id DESC LIMIT 24`).bind(category).all();const cr=await env.DB.prepare(`SELECT c.*, (SELECT r2_key FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) rk,(SELECT asset_url FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) au FROM creations c WHERE c.category=? ORDER BY CASE c.status WHEN 'Available Now' THEN 0 WHEN 'Seasonal' THEN 1 WHEN 'Sold' THEN 2 ELSE 3 END,c.id DESC LIMIT 24`).bind(category).all();const avail=(pr.results||[]).map(x=>({kind:'product',id:x.id,code:x.code,name:x.name,category:x.category,price_pkr:x.price_pkr,discount_value:x.discount_value,status:x.status,image_url:x.primary_r2_key?'/media/'+x.primary_r2_key.split('/').map(encodeURIComponent).join('/'):(x.primary_asset_url||'')}));const refs=(cr.results||[]).map(x=>({kind:'creation',code:x.code,name:x.title,category:x.category,status:x.status,image_url:x.rk?'/media/'+x.rk.split('/').map(encodeURIComponent).join('/'):(x.au||''),custom_possible:!!x.custom_possible}));return json({ok:true,mode:'category',category,answer:`Here are ${category.toLowerCase()} available to buy, followed by Our Creations for similar/custom requests.`,available:avail,creations:refs,options:['Shop Products','Request Similar']});}
  if(/event|stall|exhibition|karachi|lahore|islamabad|peshawar|multan|city/i.test(message)){const er=await env.DB.prepare("SELECT id,title,city,venue,event_date,timing,stall_no,status FROM events WHERE event_date>=date('now') ORDER BY event_date,id LIMIT 10").all();return json({ok:true,mode:'events',answer:(er.results||[]).length?'Here are our upcoming events.':'No upcoming event is currently announced.',events:er.results||[],options:['Upcoming Events']});}
  if(/payment|pay|bank|qr|card|cod/i.test(message))return json({ok:true,mode:'info',answer:'SS Collections accepts advance payment only; COD is not available. After placing an order, use the generated order number as the payment reference. Payment is treated as confirmed only after authorised confirmation.',options:['My Order','Payment Information']});
  if(/return|refund|damage|damaged|wrong product|exchange/i.test(message))return json({ok:true,mode:'info',answer:'Returns can be requested for a wrong product, confirmed workmanship defect, or transit damage. Refund processing begins after the returned item is received and the issue is verified; approved refunds are processed within 15 working days.',options:['Returns','My Order','Request Help']});
  if(/track|delivery|dispatch|parcel|courier/i.test(message))return json({ok:true,mode:'prompt_order',answer:'Please enter your SS Collections order number (for example SS-2026-123456). I will show payment, preparation, dispatch and tracking information together.',options:['My Order']});
  if(/shop|product|products|buy/i.test(message))return json({ok:true,mode:'category_menu',answer:'Choose a product category or enter one or more product codes.',options:['Bags','Dresses','Jewellery','Hair Accessories','Travel Bags','Winter Collection','Summer Collection','Wedding','Home Décor','Shoes']});
  if(/handmade|hand made/i.test(message))return json({ok:true,mode:'info',answer:'Yes. SS Collections focuses on handmade and customised pieces. Our Handmade Journey shows how selected items are created.',links:[{label:'View Handmade Journey',href:'#story'}]});
  if(/custom order|customised|customized/i.test(message))return json({ok:true,mode:'info',answer:'Custom orders are available. You may choose a past creation through Request Similar or submit your own requirements.',links:[{label:'Request Similar',action:'request_similar'},{label:'Custom Order',href:'#custom'}]});
  if(/discount/i.test(message))return json({ok:true,mode:'info',answer:'Current product discounts are shown with each available product. We also offer event discounts, with an extra special discount for customers who select “Yes – Interested” for an event.',links:[{label:'Shop',action:'shop'},{label:'Events',action:'events'}]});
  if(/contact|whatsapp/i.test(message))return json({ok:true,mode:'info',answer:'You can contact SS Collections on WhatsApp at 0346 0113599.',links:[{label:'Open WhatsApp',href:'https://wa.me/923460113599'}]});
  if(/journey|making/i.test(message))return json({ok:true,mode:'info',answer:'You can see selected making-process pictures and videos in our Handmade Journey.',links:[{label:'View Handmade Journey',href:'#story'}]});
  return menu();}
 if(p.startsWith('/media/')&&m==='GET'){const key=decodeURIComponent(p.slice('/media/'.length));if(/^(orders|returns|payments)\//.test(key)){const a=await requireUser(request,env);if(a.error)return a.error;}const obj=await env.FILES.get(key);if(!obj)return new Response('Not found',{status:404});const headers=new Headers();obj.writeHttpMetadata(headers);headers.set('etag',obj.httpEtag);headers.set('cache-control','private, max-age=3600');return new Response(obj.body,{headers});}
 if(p.startsWith('/api/'))return json({ok:false,error:'API route not found'},404);
 return env.ASSETS.fetch(request);
 }catch(e){console.error(JSON.stringify({event:'request_error',path:p,error:String(e?.message||e)}));return json({ok:false,error:'UAT API error',detail:String(e?.message||e),path:p},500)}} ,async scheduled(controller,env,ctx){ctx.waitUntil(releaseExpired(env));}};
