const CATEGORIES=['Bags','Dresses','Jewellery','Hair Accessories','Travel Bags','Winter Collection','Summer Collection','Wedding','Home Décor','Shoes','Other'];
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function requestJson(request){try{return await request.json()}catch{return {}}}
function mediaUrl(row){if(row?.r2_key)return '/media/'+encodeURIComponent(row.r2_key);return row?.asset_url||''}
async function releaseExpired(env){const now=new Date().toISOString();const expired=await env.DB.prepare("SELECT order_no FROM orders WHERE payment_status='pending' AND order_status IN ('reserved','payment_pending') AND payment_due_at IS NOT NULL AND payment_due_at < ?").bind(now).all();for(const o of expired.results||[]){await env.DB.batch([env.DB.prepare("UPDATE products SET status='available',reserved_order_no=NULL,reserved_until=NULL,updated_at=CURRENT_TIMESTAMP WHERE reserved_order_no=? AND status='reserved'").bind(o.order_no),env.DB.prepare("UPDATE orders SET order_status='revoked',updated_at=CURRENT_TIMESTAMP WHERE order_no=?").bind(o.order_no)]);}return expired.results?.length||0}
function orderNo(){const d=new Date();return `SS-${d.getUTCFullYear()}-${String(Date.now()).slice(-6)}`}
function discounted(p){const price=Number(p.price_pkr)||0,v=Number(p.discount_value)||0;return p.discount_type==='fixed'?Math.max(0,price-v):Math.round(price*(1-v/100))}
function safeKey(key){return key.split('/').map(encodeURIComponent).join('/')}
export default {
 async fetch(request,env){const u=new URL(request.url),p=u.pathname,m=request.method;try{
  if(p==='/api/health')return json({ok:true,app:'SS Collections by SunShah',environment:'uat',version:'4.2',d1:!!env.DB,r2:!!env.FILES});
  if(p==='/api/categories')return json({ok:true,categories:CATEGORIES});
  if(p==='/api/products'&&m==='GET'){await releaseExpired(env);const r=await env.DB.prepare(`SELECT p.*, (SELECT r2_key FROM product_media pm WHERE pm.product_id=p.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_r2_key,(SELECT asset_url FROM product_media pm WHERE pm.product_id=p.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_asset_url FROM products p ORDER BY featured DESC,id DESC`).all();return json({ok:true,products:(r.results||[]).map(x=>({...x,image_url:x.primary_r2_key?'/media/'+safeKey(x.primary_r2_key):(x.primary_asset_url||'')}))});}
  if(p.startsWith('/api/products/')&&m==='GET'){const key=decodeURIComponent(p.slice('/api/products/'.length));const product=await env.DB.prepare('SELECT * FROM products WHERE CAST(id AS TEXT)=? OR code=?').bind(key,key).first();if(!product)return json({ok:false,error:'Product not found'},404);const mr=await env.DB.prepare('SELECT * FROM product_media WHERE product_id=? ORDER BY is_primary DESC,sort_order,id').bind(product.id).all();return json({ok:true,product:{...product,media:(mr.results||[]).map(x=>({...x,url:mediaUrl(x)}))}});}
  if(p==='/api/creations'&&m==='GET'){const r=await env.DB.prepare(`SELECT c.*, (SELECT r2_key FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_r2_key,(SELECT asset_url FROM creation_media cm WHERE cm.creation_id=c.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) primary_asset_url FROM creations c ORDER BY id DESC`).all();return json({ok:true,creations:(r.results||[]).map(x=>({...x,image_url:x.primary_r2_key?'/media/'+safeKey(x.primary_r2_key):(x.primary_asset_url||'')}))});}
  if(p==='/api/events'&&m==='GET'){const r=await env.DB.prepare('SELECT * FROM events ORDER BY event_date,id DESC').all();return json({ok:true,events:r.results||[]});}
  if(p==='/api/journey'&&m==='GET'){const r=await env.DB.prepare('SELECT * FROM handmade_journey WHERE is_published=1 ORDER BY sort_order,id DESC').all();return json({ok:true,journey:(r.results||[]).map(x=>({...x,url:x.r2_key?'/media/'+safeKey(x.r2_key):x.external_url}))});}
  if(p==='/api/reviews'&&m==='GET'){const productId=u.searchParams.get('product_id');const q=productId?env.DB.prepare('SELECT * FROM reviews WHERE is_approved=1 AND product_id=? ORDER BY id DESC').bind(productId):env.DB.prepare('SELECT * FROM reviews WHERE is_approved=1 ORDER BY id DESC LIMIT 100');const r=await q.all();return json({ok:true,reviews:r.results||[]});}
  if(p==='/api/reviews'&&m==='POST'){const b=await requestJson(request);const rating=Number(b.rating);if(!(rating>=1&&rating<=5))return json({ok:false,error:'Rating from 1 to 5 is required'},400);await env.DB.prepare('INSERT INTO reviews(product_id,order_id,customer_name,rating,feedback,service_rating,is_approved) VALUES(?,?,?,?,?,?,0)').bind(b.product_id||null,b.order_id||null,b.customer_name||'Customer',rating,b.feedback||'',b.service_rating||null).run();return json({ok:true,message:'Feedback received and awaiting approval'},201);}
  if(p==='/api/orders'&&m==='POST'){await releaseExpired(env);const b=await requestJson(request);if(!b.customer_name||!b.whatsapp||!Array.isArray(b.product_ids)||!b.product_ids.length)return json({ok:false,error:'customer_name, whatsapp and product_ids are required'},400);const ids=[...new Set(b.product_ids.map(Number).filter(Number.isFinite))];const q=ids.map(()=>'?').join(',');const pr=await env.DB.prepare(`SELECT * FROM products WHERE id IN (${q})`).bind(...ids).all();if((pr.results||[]).length!==ids.length)return json({ok:false,error:'One or more products were not found'},404);if(pr.results.some(x=>x.status!=='available'))return json({ok:false,error:'One or more unique products are no longer available'},409);const hours=Math.min(168,Math.max(1,Number((await env.DB.prepare("SELECT value FROM settings WHERE key='reservation_hours'").first())?.value||24)));const no=orderNo(),due=new Date(Date.now()+hours*3600000).toISOString(),amount=pr.results.reduce((s,x)=>s+discounted(x),0);await env.DB.prepare(`INSERT INTO orders(order_no,customer_name,whatsapp,email,address,city,amount_pkr,payment_method,payment_due_at,payment_reference,payment_status,order_status) VALUES(?,?,?,?,?,?,?,?,?,?,'pending','reserved')`).bind(no,b.customer_name,b.whatsapp,b.email||'',b.address||'',b.city||'',amount,b.payment_method||'bank',due,no).run();const order=await env.DB.prepare('SELECT id FROM orders WHERE order_no=?').bind(no).first();for(const x of pr.results){await env.DB.prepare('INSERT INTO order_items(order_id,product_id,unit_price_pkr,product_snapshot_name,product_snapshot_code) VALUES(?,?,?,?,?)').bind(order.id,x.id,discounted(x),x.name,x.code).run();const upd=await env.DB.prepare("UPDATE products SET status='reserved',reserved_order_no=?,reserved_until=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='available'").bind(no,due,x.id).run();if(!upd.meta?.changes)throw new Error('Reservation conflict');}const first=pr.results[0],media=await env.DB.prepare('SELECT r2_key,asset_url FROM product_media WHERE product_id=? ORDER BY is_primary DESC,sort_order,id LIMIT 1').bind(first.id).first();const pic=media?.r2_key?'/media/'+safeKey(media.r2_key):(media?.asset_url||'');return json({ok:true,order_no:no,amount_pkr:amount,payment_due_at:due,payment_reference:no,product_picture:pic,whatsapp_message:`SS Collections by SunShah: Order ${no} received. Amount PKR ${amount.toLocaleString('en-PK')}. Payment is due by ${new Date(due).toLocaleString('en-PK',{timeZone:'Asia/Karachi'})}. Please quote ${no} as your payment reference. If payment is not received by the due date, the reservation may be revoked and the unique product may be made available to another customer.`},201);}
  if(p.startsWith('/api/orders/')&&m==='GET'){await releaseExpired(env);const no=decodeURIComponent(p.slice('/api/orders/'.length));const o=await env.DB.prepare('SELECT * FROM orders WHERE order_no=?').bind(no).first();if(!o)return json({ok:false,error:'Order not found'},404);const ir=await env.DB.prepare('SELECT oi.*,p.status product_status FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=?').bind(o.id).all();return json({ok:true,order:{...o,items:ir.results||[]}});}
  if(p.startsWith('/media/')&&m==='GET'){const key=decodeURIComponent(p.slice('/media/'.length));const obj=await env.FILES.get(key);if(!obj)return new Response('Not found',{status:404});const headers=new Headers();obj.writeHttpMetadata(headers);headers.set('etag',obj.httpEtag);headers.set('cache-control','public, max-age=3600');return new Response(obj.body,{headers});}
  if(p.startsWith('/api/'))return json({ok:false,error:'API route not found'},404);
  return env.ASSETS.fetch(request);
 }catch(e){return json({ok:false,error:'UAT API error',detail:String(e?.message||e)},500)}} ,
 async scheduled(controller,env,ctx){ctx.waitUntil(releaseExpired(env));}
};
